version: '3.3'
services:
  app:
    build:
      context: .
      dockerfile: .docker/Dockerfile
    image: fms
    ports:
      - 8080:80
    volumes:
      - .:/var/www/html
      - ../uploads:/var/www/html/uploads
    links:
      - mysql
  mysql:
    image: mysql:5.7
    ports:
      - 3307:3306
    environment:
      MYSQL_DATABASE: fms
      MYSQL_USER: root
      MYSQL_PASSWORD: ash1201033m
      MYSQL_ROOT_PASSWORD: ash1201033m
    volumes:
      - ./../fms_mysql:/var/lib/mysql
